### ISSUE TITLE
[Feature request] JSON API

### ISSUE THREAD

**Issue by KaKi87** [ProjectArkadiaTeam/trigedasleng#2]
I would like to be able to make API requests that returns JSON, in order to add trigedasleng features to my Discord The 100 bot, like :
- Search, define and translate english and trig words
- Listen to trigedasleng pronunciations
- Browse all dictionnaries

Thanks.

**Comment by SKroell** [comment]
I've done a quick implementation of the search API in 9d3db7ae09c8ce6c6b046f85bdb914128fb5b5dd
Example: https://trigedasleng.net/api/api?action=search&query=love

**Comment by SKroell** [comment]
Added getDictionary action as well.
Example: https://trigedasleng.net/api/api?action=getDictionary&filter=canon

**Comment by KaKi87** [comment]
This is very nice. Thanks :)

**Comment by KaKi87** [comment]
Here is my first NodeJS implementation of your trigedasleng.net's API (not published to npmjs yet) : https://git.kaki87.net/KaKi87/trigedasleng-api

However, the following words, listed in dictionary, are failing the search endpoint and returns empty body (not even `[]`) :

```
ai
ai op
but
don
em
en
ha
in
klir
lou
no
nou
o
oda
op
ro
sadon
sef
sha
vout
vout in
weron
wo
woda
yo
you
```

Could you also convert HTML entities to Unicode in order to automatically escape them while parsing JSON ? Thanks !

While working on the dictionary fetch endpoint, I collected some stats that you'll find interesting...

### Word/phrase types and count

```
+--------------------------+-----+
| noun                     | 910 |
| verb                     | 508 |
| adjective                | 361 |
| adverb                   |  65 |
| UNSPECIFIED              |  33 |
| phrase                   |  32 |
| pronoun                  |  32 |
| proper noun              |  26 |
| interjection             |  15 |
| preposition              |  14 |
| auxiliary                |   9 |
| conjunction              |   7 |
| satellite                |   4 |
| idiom                    |   4 |
| noun/adjective/adverb    |   2 |
| (feeling) noun           |   1 |
| noun/adjective           |   1 |
| (leather) verb           |   1 |
| (meat) verb              |   1 |
| (oneself) verb           |   1 |
| (oneself) adjective      |   1 |
| (endearment) noun        |   1 |
| (animal, e.g. wolf) noun |   1 |
| (ironic) noun            |   1 |
| UNDEFINED                |   1 |
| (s.o./s.t.) verb         |   1 |
| (derogatory) noun        |   1 |
+--------------------------+-----+
```

### Words with unspecified type

```
bei
tamon
azgeda
﻿af
asol
bastab
bastabplei
belen bouz
belplei
blidplei
blouplei
bomz-de
du posh boton-de
dula kainnes
enthing
ge skrud op
gon bum
gou of
heri sich
heyo
kod in
komo
nou stepnes
os job
oseim
pleithing
pleni os
sen blinka daun
shedi
soukei
yuni
azgeda
nou stepnes
```

### Words with unspecified translation

```
set op (item)
```

### Weirdly named words

]
gauj ...au
```

### Duplicate words having the same meaning in different dictionaries

```
af
flou thru
kodchuwa
shilkrola
wocha
```

### Audio

https://trigedasleng.net/audio/ ► directory index active ?

#### Missing files

```
https://trigedasleng.net/audio/s3/NYKO_302_17.mp3
https://trigedasleng.net/audio/s2/LEXA_214_2.mp3
https://trigedasleng.net/audio/s3/BOUNTY_HUNTER_302_3.mp3
https://trigedasleng.net/audio/s3/BOUNTY_HUNTER_302_4.mp3
https://trigedasleng.net/audio/s3/INDRA_302_6.mp3
https://trigedasleng.net/audio/s3/ROAN_302_7.mp3
https://trigedasleng.net/audio/s3/ROAN_302_12.mp3
https://trigedasleng.net/audio/s3/ROAN_302_14.mp3
https://trigedasleng.net/audio/s3/AZGEDA_SCOUT_302_15.mp3
https://trigedasleng.net/audio/s3/AZGEDA_SCOUT_302_8.mp3
https://trigedasleng.net/audio/s3/LINCOLN_302_16.mp3
https://trigedasleng.net/audio/s3/AZGEDA_SCOUT_302_9.mp3
https://trigedasleng.net/audio/s3/AZGEDA_SCOUT_302_13.mp3
https://trigedasleng.net/audio/s3/INDRA_302_5.mp3
https://trigedasleng.net/audio/s3/LINCOLN_302_20.mp3
https://trigedasleng.net/audio/s2/VOICE_214_1.mp3
https://trigedasleng.net/audio/s3/LINCOLN_302_19.mp3
https://trigedasleng.net/audio/s3/ROAN_302_10.mp3
https://trigedasleng.net/audio/s3/LINCOLN_302_18.mp3
https://trigedasleng.net/audio/s2/LEXA_214_11.mp3
https://trigedasleng.net/audio/s3/adr_2.mp3
```

I guess that the trigedasleng database is globally lacking of structure and controls, and there would be a lot of migrations to do.

But, until then, these are priority issues to work on !

Good luck :)

**Comment by KaKi87** [comment]
**Why isn't the audio directory on the repo ?**

Here are the missing files in the same order.
```
https://dedalvs.com/work/the-100/s3/302/audio/NYKO_302_17.mp3
https://dedalvs.com/work/the-100/s2/214/audio/LEXA_214_2.mp3
https://dedalvs.com/work/the-100/s3/302/audio/BOUNTY_HUNTER_302_3.mp3
https://dedalvs.com/work/the-100/s3/302/audio/BOUNTY_HUNTER_302_4.mp3
https://dedalvs.com/work/the-100/s3/302/audio/INDRA_302_6.mp3
https://dedalvs.com/work/the-100/s3/302/audio/ROAN_302_7.mp3
https://dedalvs.com/work/the-100/s3/302/audio/ROAN_302_12.mp3
https://dedalvs.com/work/the-100/s3/302/audio/ROAN_302_14.mp3
https://dedalvs.com/work/the-100/s3/302/audio/AZGEDA_SCOUT_302_15.mp3
https://dedalvs.com/work/the-100/s3/302/audio/AZGEDA_SCOUT_302_8.mp3
https://dedalvs.com/work/the-100/s3/302/audio/LINCOLN_302_16.mp3
https://dedalvs.com/work/the-100/s3/302/audio/AZGEDA_SCOUT_302_9.mp3
https://dedalvs.com/work/the-100/s3/302/audio/AZGEDA_SCOUT_302_13.mp3
https://dedalvs.com/work/the-100/s3/302/audio/INDRA_302_5.mp3
https://dedalvs.com/work/the-100/s3/302/audio/LINCOLN_302_20.mp3
https://dedalvs.com/work/the-100/s2/214/audio/VOICE_214_1.mp3
https://dedalvs.com/work/the-100/s3/302/audio/LINCOLN_302_19.mp3
https://dedalvs.com/work/the-100/s3/302/audio/ROAN_302_10.mp3
https://dedalvs.com/work/the-100/s3/302/audio/LINCOLN_302_18.mp3
https://dedalvs.com/work/the-100/s2/214/audio/LEXA_214_11.mp3
https://dedalvs.com/work/the-100/s3/302/audio/adr_2.mp3
```

**Comment by SKroell** [comment]
All missing audio clips have been upload and added to to repo as well.
I'll keep the audio folder index active as its not really a security issue and maybe someone wants to look through it.

Also UTF-8 encoding is forced now, so that should fix the API issues where nothing is returned.

**Comment by KaKi87** [comment]
So here's the updated problems list.

- [x] Empty body
- [ ] HTML entities ⚠️ *blocking issue*
- [ ] Non-standard word/sentence types
- [ ] Unspecified word/sentence types ⚠️ *blocking issue*
- [x] Weird words
- [x] Duplicate meanings
- [x] Missing audio files
- [ ] Spaces & new lines characters

Thanks !

**Comment by SKroell** [comment]
Alls word should now have a specification and I've removed most of the odd ones.
Spaces & new lines characters has been removed from at least 99% of entries. Let me know if you find that I've missed some.

Still working on HTML entities. I'm going to clean it in the db instead of cleaning it on runtime, so it might take a bit.

**Comment by KaKi87** [comment]
Oh I didn't knew the issue was from the database. Is the [sql/data.sql](https://github.com/ProjectArkadiaTeam/trigedasleng/blob/master/sql/data.sql) file up to date ?

**Comment by KaKi87** [comment]
Here's the final list of missing word/sentence types :
```
bei
dula kainnes
inayu
```

**Comment by SKroell** [comment]
And here I thought I got all of them. The last 3 should be fixed now... 
Both sql files are up to date as of 8dcf218 and I believe I've fixed all encoding issues.

**Comment by KaKi87** [comment]
Missing definitions :
```
bouwiyon
kan
kapengaun
slipfou
```

**Comment by KaKi87** [comment]
@SKroell Please look at the updated [Trigedasleng database test report](https://git.kaki87.net/KaKi87/trigedasleng-api/src/branch/master/test) (25 words with missing type, 477 words with missing etymology).
This report can now be generated automatically using a custom script that I added to the API wrapper.
Thanks

**Comment by SKroell** [comment]
@KaKi87 They should all be fixed now. Since most etymology issues comes from the non-canon dictionary and with no (easy) way to find out the original etymology they now show 'Unknown' instead of nothing.
