### ISSUE TITLE
Encoding error in DB for some translations containing single quote(s)

### ISSUE THREAD

**Issue by ZoeS17** [ProjectArkadiaTeam/trigedasleng#35]
It appears there seems to be a double UTF-8 encoding error on the following translations ids:
- 1090
- 1094 - 1099
- 1101 - 1103
- 1107
A possible [SO question](https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5) to help us fix it should it be a problem going forward, though I believe it maybe from an older insert or code state.

~~Original report on Discord by Swoop.

**Comment by SKroell** [comment]
As you said yourself I believe the issue has been around for a while and has most likely happened as part of an data import. For now I've just manually edited the translation ids in question.

If the issue where to popup again, we can look at what is causing it.
